version: 2

jobs:
  build:
    docker:
      # the Docker image with Cypress dependencies
      - image: cypress/included:6.5.0
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/app
    parallelism: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v2-deps-{{ .Branch }}-
            - v2-deps-
      - run: npm ci
      - run: npm install cypress --save-dev
      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: NODE_OPTIONS
          command: unset NODE_OPTIONS
      - run:
          name: Running tests
          command: npx cypress run --env=configFile=qas4
      - run:
          name: Report
          command: npm run postcypress:run
      - store_test_results:
          path: reports
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots